function stats = plot_optimum_validation( ...
    case_labels, ...
    NOx_pred, NOx_std, NOx_CFD, ...
    T_pred, T_std, T_CFD, ...
    T_min)

%% PLOT_OPTIMUM_VALIDATION
%
% Report-ready CFD verification plot for GP-predicted optimum candidates.
%
% PANEL (a): NOx
%   - GP predicted physical NOx mean
%   - +/- 1 GP physical standard deviation
%   - CFD result
%   - absolute error
%   - relative error
%   - standardized prediction deviation in sigma
%
% PANEL (b): Temperature
%   - GP predicted outlet temperature
%   - +/- 1 GP standard deviation
%   - CFD result
%   - minimum outlet-temperature constraint
%   - absolute error
%   - standardized prediction deviation in sigma
%
% IMPORTANT:
% Use the historical prediction and uncertainty that existed when
% each OS candidate was proposed.


%% =========================================================
% 1. Prepare inputs
%% =========================================================

case_labels = string(case_labels(:));

NOx_pred = NOx_pred(:);
NOx_std  = NOx_std(:);
NOx_CFD  = NOx_CFD(:);

T_pred = T_pred(:);
T_std  = T_std(:);
T_CFD  = T_CFD(:);

n_cases = length(case_labels);

x = (1:n_cases)';


%% Input checks

if any([
        length(NOx_pred)
        length(NOx_std)
        length(NOx_CFD)
        length(T_pred)
        length(T_std)
        length(T_CFD)] ~= n_cases)

    error('All data vectors must contain the same number of cases.');

end

if any(NOx_pred <= 0) || any(NOx_CFD <= 0)
    error('NOx values must be positive.');
end

if any(NOx_std < 0) || any(T_std < 0)
    error('Standard deviations cannot be negative.');
end


%% =========================================================
% 2. Error metrics
%% =========================================================

%% NOx

NOx_abs_error = ...
    abs(NOx_CFD - NOx_pred);

NOx_rel_error = ...
    NOx_abs_error ./ abs(NOx_CFD) .* 100;

% Error expressed relative to physical GP standard deviation.
NOx_sigma_ratio = ...
    NOx_abs_error ./ max(NOx_std,1e-12);


%% Temperature

T_abs_error = ...
    abs(T_CFD - T_pred);

% Number of GP standard deviations between prediction and CFD result.
T_sigma_ratio = ...
    T_abs_error ./ max(T_std,1e-12);


%% =========================================================
% 3. Figure setup
%% =========================================================

fig = figure( ...
    'Color','w', ...
    'Units','centimeters', ...
    'Position',[2 2 18 15.5], ...
    'Renderer','painters');


font_name = 'Times New Roman';

font_axis  = 9;
font_title = 10;
font_label = 8.5;
font_case  = 9;


%% =========================================================
% 4. PANEL (a): NOx
%% =========================================================

ax_NOx = axes( ...
    'Parent',fig, ...
    'Position',[0.11 0.690 0.855 0.255]);


%% GP prediction +/- 1 sigma

errorbar( ...
    ax_NOx, ...
    x, ...
    NOx_pred, ...
    NOx_std, ...
    NOx_std, ...
    'o', ...
    'LineStyle','none', ...
    'MarkerSize',6, ...
    'LineWidth',1.15, ...
    'CapSize',7, ...
    'DisplayName','GP prediction \pm 1\sigma');

hold(ax_NOx,'on');


%% CFD observations

plot( ...
    ax_NOx, ...
    x, ...
    NOx_CFD, ...
    'x', ...
    'LineStyle','none', ...
    'MarkerSize',7, ...
    'LineWidth',1.4, ...
    'DisplayName','CFD');


%% NOx axis limits

NOx_min = ...
    min([NOx_CFD; NOx_pred-NOx_std]);

NOx_max = ...
    max([NOx_CFD; NOx_pred+NOx_std]);

NOx_range = NOx_max - NOx_min;

if NOx_range <= 0
    NOx_range = NOx_max;
end

ylim( ...
    ax_NOx, ...
    [ ...
    max(0, NOx_min - 0.10*NOx_range), ...
    NOx_max + 0.10*NOx_range ...
    ]);


xlim(ax_NOx,[0.5 n_cases+0.5]);


set( ...
    ax_NOx, ...
    'XTick',x, ...
    'XTickLabel',[], ...
    'FontName',font_name, ...
    'FontSize',font_axis, ...
    'LineWidth',0.8);


ylabel( ...
    ax_NOx, ...
    'NO outlet mass fraction [-]', ...
    'FontName',font_name, ...
    'FontSize',font_axis);


title( ...
    ax_NOx, ...
    '(a) NO prediction and CFD verification', ...
    'FontName',font_name, ...
    'FontSize',font_title, ...
    'FontWeight','bold');


grid(ax_NOx,'on');
box(ax_NOx,'on');


leg1 = legend( ...
    ax_NOx, ...
    'Location','northeast', ...
    'Interpreter','tex');

set( ...
    leg1, ...
    'FontName',font_name, ...
    'FontSize',8, ...
    'Box','off');


%% =========================================================
% 5. NOx metric strip
%% =========================================================

ax_NOx_info = axes( ...
    'Parent',fig, ...
    'Position',[0.11 0.535 0.855 0.135]);


xlim(ax_NOx_info,[0.5 n_cases+0.5]);
ylim(ax_NOx_info,[0 1]);

axis(ax_NOx_info,'off');


for i = 1:n_cases

    %% Case identifier

    text( ...
        ax_NOx_info, ...
        x(i), ...
        0.88, ...
        char(case_labels(i)), ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','middle', ...
        'FontName',font_name, ...
        'FontSize',font_case, ...
        'FontWeight','bold');


    %% Metrics

    metric_string = sprintf( ...
        ['abs. err. = %.2e\n' ...
         'rel. err. = %.1f%%\n' ...
         '%.2f\\sigma'], ...
        NOx_abs_error(i), ...
        NOx_rel_error(i), ...
        NOx_sigma_ratio(i));


    text( ...
        ax_NOx_info, ...
        x(i), ...
        0.48, ...
        metric_string, ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','middle', ...
        'Interpreter','tex', ...
        'FontName',font_name, ...
        'FontSize',font_label);

end


%% =========================================================
% 6. PANEL (b): Temperature
%% =========================================================

ax_T = axes( ...
    'Parent',fig, ...
    'Position',[0.11 0.225 0.855 0.255]);


%% GP prediction +/- 1 sigma

errorbar( ...
    ax_T, ...
    x, ...
    T_pred, ...
    T_std, ...
    T_std, ...
    'o', ...
    'LineStyle','none', ...
    'MarkerSize',6, ...
    'LineWidth',1.15, ...
    'CapSize',7, ...
    'DisplayName','GP prediction \pm 1\sigma');

hold(ax_T,'on');


%% CFD observations

plot( ...
    ax_T, ...
    x, ...
    T_CFD, ...
    'x', ...
    'LineStyle','none', ...
    'MarkerSize',7, ...
    'LineWidth',1.4, ...
    'DisplayName','CFD');


%% Temperature constraint

yline( ...
    ax_T, ...
    T_min, ...
    '--', ...
    'LineWidth',1.1, ...
    'DisplayName',sprintf( ...
        'Minimum temperature, T_{min} = %.2f K', ...
        T_min));


%% Temperature limits

T_min_plot = ...
    min([T_CFD; T_pred-T_std; T_min]);

T_max_plot = ...
    max([T_CFD; T_pred+T_std; T_min]);

T_range = T_max_plot - T_min_plot;

if T_range <= 0
    T_range = 1;
end


ylim( ...
    ax_T, ...
    [ ...
    T_min_plot - 0.08*T_range, ...
    T_max_plot + 0.10*T_range ...
    ]);


xlim(ax_T,[0.5 n_cases+0.5]);


set( ...
    ax_T, ...
    'XTick',x, ...
    'XTickLabel',[], ...
    'FontName',font_name, ...
    'FontSize',font_axis, ...
    'LineWidth',0.8);


ylabel( ...
    ax_T, ...
    'Outlet temperature [K]', ...
    'FontName',font_name, ...
    'FontSize',font_axis);


title( ...
    ax_T, ...
    '(b) Outlet temperature prediction and CFD verification', ...
    'FontName',font_name, ...
    'FontSize',font_title, ...
    'FontWeight','bold');


grid(ax_T,'on');
box(ax_T,'on');


leg2 = legend( ...
    ax_T, ...
    'Location','northeast', ...
    'Interpreter','tex');

set( ...
    leg2, ...
    'FontName',font_name, ...
    'FontSize',8, ...
    'Box','off');


%% =========================================================
% 7. Temperature metric strip
%% =========================================================

ax_T_info = axes( ...
    'Parent',fig, ...
    'Position',[0.11 0.075 0.855 0.120]);


xlim(ax_T_info,[0.5 n_cases+0.5]);
ylim(ax_T_info,[0 1]);

axis(ax_T_info,'off');


for i = 1:n_cases

    %% Case identifier

    text( ...
        ax_T_info, ...
        x(i), ...
        0.80, ...
        char(case_labels(i)), ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','middle', ...
        'FontName',font_name, ...
        'FontSize',font_case, ...
        'FontWeight','bold');


    %% Temperature metrics

    metric_string = sprintf( ...
        ['abs. err. = %.2f K\n' ...
         '%.2f\\sigma'], ...
        T_abs_error(i), ...
        T_sigma_ratio(i));


    text( ...
        ax_T_info, ...
        x(i), ...
        0.39, ...
        metric_string, ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','middle', ...
        'Interpreter','tex', ...
        'FontName',font_name, ...
        'FontSize',font_label);

end


%% =========================================================
% 8. Return statistics
%% =========================================================

stats = table( ...
    case_labels, ...
    NOx_pred, ...
    NOx_std, ...
    NOx_CFD, ...
    NOx_abs_error, ...
    NOx_rel_error, ...
    NOx_sigma_ratio, ...
    T_pred, ...
    T_std, ...
    T_CFD, ...
    T_abs_error, ...
    T_sigma_ratio, ...
    'VariableNames',{ ...
        'Case', ...
        'NOx_GP', ...
        'NOx_GP_std', ...
        'NOx_CFD', ...
        'NOx_AbsError', ...
        'NOx_RelError_percent', ...
        'NOx_Error_sigma', ...
        'T_GP_K', ...
        'T_GP_std_K', ...
        'T_CFD_K', ...
        'T_AbsError_K', ...
        'T_Error_sigma'});


%% =========================================================
% 9. Command-window output
%% =========================================================

fprintf('\n');
fprintf('=============================================\n');
fprintf('OPTIMUM CFD VALIDATION\n');
fprintf('=============================================\n\n');

disp(stats);


end